# Generated by Django 2.2.6 on 2020-02-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddiconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seeker',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
