# Generated by Django 2.2.6 on 2020-02-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddiconnect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
