# Generated by Django 2.2.6 on 2020-02-11 23:05

import buddiconnect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddiconnect', '0002_auto_20200211_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to=buddiconnect.models.get_image_path),
        ),
    ]
