# Generated by Django 2.2.6 on 2020-02-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddiconnect', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='zipCode',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
