# Generated by Django 2.2.6 on 2020-02-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddiconnect', '0004_auto_20200219_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipCode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
